In [ ]:
import numpy as np


In [ ]:
np.__version__

'1.23.5'

In [ ]:
#creating one array
arr=np.array([1,2,3,4,5])
arr
type(arr)

numpy.ndarray

In [ ]:
a=['mca',55,24,72.5]
arr2=np.array(a)
print(type(arr2))
arr2

<class 'numpy.ndarray'>


array(['mca', '55', '24', '72.5'], dtype='<U32')

In [ ]:
#array using tuple
arr3=np.array((1,2,3,4,5))
print(arr3)
type(arr3)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating array using tuple
t1=(55,66,77,88)
arr4=np.array(t1)
print(type(arr4))
arr4

<class 'numpy.ndarray'>


array([55, 66, 77, 88])

In [ ]:
#2-d array
twod=np.array([[1,2,3],[4,5,6]])
print(twod)
twod.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
#create a 3-d araay with two 2-d array
threearr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threearr)
np.shape(threearr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [ ]:
#access 1-D arrays
arr=np.array([1,2,3,4])
print(arr[0])
print(arr[2])
#get the second and fourth element from the following array and add them
a=arr[1]+arr[3]
print(a)

1
3
6


In [ ]:
#access the element on the first row,second column
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])
#access the element on the 2nd row , 5th column
print(arr[1,4])

2
10


In [ ]:
#Access the third elemnet of the second array of the first array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
#Access the second element of the first of the second array
print(arr[1,0,1])
#Access the second element of the second array of second array
print(arr[1,1,1])

6
8
11
