In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
df=pd.read_csv("/content/result.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Maths         5 non-null      int64 
 1   Comp Science  5 non-null      int64 
 2   Result        5 non-null      object
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes


In [ ]:
df.head()

Maths  Comp Science Result
0      4             3   Fail
1      6             7   Pass
2      7             8   Pass
3      5             5   Fail
4      8             8   Pass

In [ ]:
x=df.drop("Result",axis=1)

In [ ]:
y=df.Result

In [ ]:
print(x)
print(y)

   Maths  Comp Science
0      4             3
1      6             7
2      7             8
3      5             5
4      8             8
0    Fail
1    Pass
2    Pass
3    Fail
4    Pass
Name: Result, dtype: object


In [ ]:
KNN=KNeighborsClassifier(n_neighbors=2)

In [ ]:
KNN.fit(x,y)

KNeighborsClassifier(n_neighbors=2)

In [ ]:
pred=KNN.predict([[6,8]])
pred

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['Pass'], dtype=object)

In [ ]:
KNN.predict([[2,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['Fail'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report, confusion_matrix,accuracy_score

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
KNN.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [ ]:
y_pred=KNN.predict(x_test)

In [ ]:
y_pred

array(['Fail', 'Fail'], dtype=object)

In [ ]:
cmf=confusion_matrix(y_test,y_pred)
tm,fp,fn,tp=cmf.ravel()

In [ ]:
cmf

array([[0, 0],
       [2, 0]])

In [ ]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.0

In [ ]:
pre=precision_score(y_test,y_pred,average=None)
pre

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([0., 0.])

In [ ]:
recall=recall_score(y_test,y_pred,average=None)
recall

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([0., 0.])

In [ ]:
f1score=f1_score(y_test,y_pred,average=None)
f1score

array([0., 0.])

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,y_pred,target_names=['0','1']))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       2.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [ ]:
df2=pd.read_csv("/content/Iris.csv")
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
df2.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df2.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [ ]:
x1=df2.drop("Species",axis=1)

In [ ]:
y1=df2.Species

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x1,y1,test_size=0.3,random_state=42)

In [ ]:
model=KNeighborsClassifier()

In [ ]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred=model.predict(x_test)
y_pred.shape

(45,)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

In [ ]:
acc = accuracy_score(y_test, y_pred)
acc

1.0

In [ ]:
pre = precision_score(y_test, y_pred, average = None)
pre

array([1., 1., 1.])

In [ ]:
rec = recall_score(y_test, y_pred, average = None)
rec

array([1., 1., 1.])

In [ ]:
f1 = f1_score(y_test, y_pred, average = None)
f1

array([1., 1., 1.])

In [ ]:
print(classification_report(y_test, y_pred, target_names=('Setosa', 'Virginica', 'Versicolor')))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        19
   Virginica       1.00      1.00      1.00        13
  Versicolor       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

