In [2]:
#Slicing Arrays
#Slicing in python means taking elements from one given index to another given index
#We pass slice instead of index like this [start:end]

import numpy as np

#SLice element from index 1 to index 5 from the following array:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [3]:
#Slice Elements from index 4 to the end of the array:
arr[4:]

array([5, 6, 7])

In [4]:
#Slice Elements from begining to index 4 (not included):
arr[:4]

array([1, 2, 3, 4])

In [8]:
#Return every other element from index 1 to index 5:
arr[1:6:2]

array([2, 4, 6])

In [6]:
#Slice from the index 3 from the end to index 1 from the end:
arr[-3:-1]

array([5, 6])

In [9]:
#Return Every other element from the entire array :\
arr[::2]

array([1, 3, 5, 7])

In [10]:
#Slicing 2-D Arrays
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#From the second element , slice elements from index 1 to index 4
arr2[1,1:4]

array([7, 8, 9])

In [11]:
#Array Creation
# The function Zeros creates an array full of zeros
arrz = np.zeros((4,4))
print(arrz)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
#The functions ones creates an array full of ones
arro=np.ones((3,4))
arro

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
#The function empty creates an arrays whose initial content is random and depends on the state memory
aare=np.empty((2,3))
aare

array([[ 4.96472625e-310,  0.00000000e+000,  6.86727796e-310],
       [ 6.86727882e-310, -1.53153613e+155,  6.86727796e-310]])

In [16]:
#np.eye()-Return a 2-D array with ones on the diagonal and zeros elsewhere
aari=np.eye(4)
aari

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#Operations on array
arr1 = np.array([[0, 1], [2, 3]])
arr2 = np.array([[1 ,2], [5, 2]])

print(arr1 * arr2)#Element wise product
print(arr1 @ arr2)#matrix product
print(arr1.dot(arr2))#another way for matrix product

[[ 0  2]
 [10  6]]
[[ 5  2]
 [17 10]]
[[ 5  2]
 [17 10]]


In [19]:
#Creating array of multiple dimensions

#4 dimensional array
arr1 = np.array([1, 2, 3, 4, 5], ndmin=4)
print(arr1)

#5 dimensional array
arr2 = np.array([1, 5, 3, 6, 8], ndmin=5)
print(arr2)

[[[[1 2 3 4 5]]]]
[[[[[1 5 3 6 8]]]]]
