<a href="https://colab.research.google.com/github/pratik1125/Machine-learning-ML-/blob/main/Basic_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.25.2'

In [4]:
#Declare one variable to store ndarray
arr=np.array([1,2,3,4,5,6,7])
arr
type(arr)

numpy.ndarray

In [6]:
#Convert a list to array
a=["MCA",48,8.60]
arr=np.array(a)
print(type(a),type(arr))
print(arr)

<class 'list'> <class 'numpy.ndarray'>
['MCA' '48' '8.6']


In [7]:
#Convet a tuple to array
tuple=("Pratik",47,88)
tarray=np.array(tuple)
print(type(tuple),type(tarray))
print(tarray)

<class 'tuple'> <class 'numpy.ndarray'>
['Pratik' '47' '88']


In [9]:
#Assignment
#Create a v(ariablr T1 and assign tuple to it

t1=("Pratik","Dewoo","Sawant")
#Create array from tuple
tarray=np.array(t1)
#Check the type
print(type(t1),type(tarray))
#Print the array
print(tarray)


<class 'tuple'> <class 'numpy.ndarray'>
['Pratik' 'Dewoo' 'Sawant']


In [12]:
#Dimension in array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(type(arr))
print(arr.shape)

[[1 2 3]
 [4 5 6]]
2
<class 'numpy.ndarray'>
(2, 3)


In [16]:
#3d Arrays
#arr=np.array([[[1,3,5],[4,5,6],[99,22,34],[44,48,56]]])
arr = np.array([[[1,3,4],[4,5,6]] , [[2,3,4],[4,6,9]]])
print(arr)
print(arr.ndim)
print(type(arr))
print(arr.shape)

[[[1 3 4]
  [4 5 6]]

 [[2 3 4]
  [4 6 9]]]
3
<class 'numpy.ndarray'>
(2, 2, 3)


In [18]:
#Accessing array
arr=np.array((1,2,3,4,5,6,7))
print(arr[0],arr[2])
print("Sum of two index is : ",arr[1] + arr[4] )

1 3
Sum of two index is :  7


In [22]:
# access the elements -> row (dimensions) column(index)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
# access the first row and second column
print(arr[0,1])
# access the second row and fifth column
print(arr[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
10


In [25]:
arr = np.array([[[1,3,4],[4,5,6]] , [[2,3,4],[4,6,9]]])
print(arr)
print(arr[0,1,2])
print("--------------")
# accessing the second element of the first array of the second array
print(arr[1,0,1])
# accessing the second element of the second array of the second array
print(arr[1,1,1])

[[[1 3 4]
  [4 5 6]]

 [[2 3 4]
  [4 6 9]]]
6
--------------
3
6
